### ISSUE TITLE
Clearly document non-Apache releases as such

### ISSUE THREAD

**Issue by ctubbsii** [apache/fluo-website#8]
It was pointed out on the incubator mailing list that the website lists releases which are not official Apache releases. We must fix that by removing them, or by making it clear that they are pointers to non-Apache releases from prior to joining Apache.

**Comment by keith-turner** [comment]
Commens from thread on mailing list :
- [comment 1](https://lists.apache.org/thread.html/660d9114bea175712ea52d3dd93c3265394ddf6ebd6f2046e8cd53d9@%3Cgeneral.incubator.apache.org%3E)
- [comment 2](https://lists.apache.org/thread.html/079eff075a8e2e554e9f824d4f1f31e357c05dcb8fa8e66e6acd41c6@%3Cgeneral.incubator.apache.org%3E)

**Comment by keith-turner** [comment]
PR #10

**Comment by keith-turner** [comment]
@ctubbsii  I think this can be closed

**Comment by nsamirror** [comment]
@keith-turner I agree, but I do not have permission to close the issue.
