### ISSUE TITLE
Add a link to helpwanted issues on website

### ISSUE THREAD

**Issue by keith-turner** [apache/fluo-website#85]
On the website can add a link to the following and explain that its starter issues we are looking for help doing.  Could add this to the contributing page.

https://github.com/apache/fluo/labels/helpwanted

**Comment by ctubbsii** [comment]
Could also use the same label on our other repos. Unfortunately, GitHub seems not offer "OR" so you can search for the "helpwanted" you created and the "help wanted" which typically exists by default. Neither does it make it support wildcards, so it's easy to search multiple repos, like `apache/fluo*`

This is the best I've got:
https://github.com/search?q=repo%3Aapache%2Ffluo+repo%3Aapache%2Ffluo-recipes+repo%3Aapache%2Ffluo-bytes+repo%3Aapache%2Ffluo-website+repo%3Aapache%2Ffluo-yarn+repo%3Aapache%2Ffluo-docker+label%3Ahelpwanted+type%3Aissue+state%3Aopen&type=Issues&utf8=%E2%9C%93

**Comment by keith-turner** [comment]
I didn't realize there was an existing `help wanted` label.  I can delete the label I created and tag things with that.

**Comment by keith-turner** [comment]
I changed the label to `help wanted` in all repos.  The following works now.

https://github.com/search?utf8=%E2%9C%93&q=repo%3Aapache%2Ffluo+repo%3Aapache%2Ffluo-recipes+repo%3Aapache%2Ffluo-bytes+repo%3Aapache%2Ffluo-website+repo%3Aapache%2Ffluo-yarn+repo%3Aapache%2Ffluo-docker+label%3A%22help+wanted%22+type%3Aissue+state%3Aopen&type=Issues

**Comment by ctubbsii** [comment]
It doesn't really matter. GitHub auto-creates labels for "convenience", but I actually prefer labels without a space: it makes it easier to search without needing to use quotes. It's entirely up to you. I was just lamenting the lack of a more robust query language with patterns and boolean operators in GitHub issue searching.

**Comment by keith-turner** [comment]
Some repos had the auto-created label and some did not.  I suppose its a matter of age.  Either way they all need to be made consistent.  I slightly prefer the default label over something custom because its a bit more standard.
